application: tnwwhatson
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /files
  static_dir: files
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /newMeeting.html
  static_files: /newMeeting.html
  upload: /newMeeting.html
- url: /.*
  script: home.app

libraries:
- name: jinja2
  version: latest